//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordManager.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PasswordManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add a record.
        /// </summary>
        public static string AddFormHeader {
            get {
                return ResourceManager.GetString("AddFormHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create new account.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string DataGridLogin {
            get {
                return ResourceManager.GetString("DataGridLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string DataGridPassword {
            get {
                return ResourceManager.GetString("DataGridPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resource.
        /// </summary>
        public static string DataGridResource {
            get {
                return ResourceManager.GetString("DataGridResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure wou want to delete this record?.
        /// </summary>
        public static string DeleteRecordFormHeader {
            get {
                return ResourceManager.GetString("DeleteRecordFormHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit a record.
        /// </summary>
        public static string EditFormHeader {
            get {
                return ResourceManager.GetString("EditFormHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email.
        /// </summary>
        public static string EmailAuth {
            get {
                return ResourceManager.GetString("EmailAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm.
        /// </summary>
        public static string EmailConfirmationConfirm {
            get {
                return ResourceManager.GetString("EmailConfirmationConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter 6-digit code that tou&apos;ve received by email.
        /// </summary>
        public static string EmailConfirmationHint {
            get {
                return ResourceManager.GetString("EmailConfirmationHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm your email.
        /// </summary>
        public static string EmailConfirmationTitle {
            get {
                return ResourceManager.GetString("EmailConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter Email.
        /// </summary>
        public static string EmailRequest {
            get {
                return ResourceManager.GetString("EmailRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter valid Email.
        /// </summary>
        public static string EnterValidEmail {
            get {
                return ResourceManager.GetString("EnterValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please fill all folowing fields.
        /// </summary>
        public static string FillAllFields {
            get {
                return ResourceManager.GetString("FillAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string FormCancel {
            get {
                return ResourceManager.GetString("FormCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fields can&apos;t be empty.
        /// </summary>
        public static string FormFillAllFields {
            get {
                return ResourceManager.GetString("FormFillAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string FormLogin {
            get {
                return ResourceManager.GetString("FormLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string FormPassword {
            get {
                return ResourceManager.GetString("FormPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recource.
        /// </summary>
        public static string FormRecource {
            get {
                return ResourceManager.GetString("FormRecource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please fiil all following fields.
        /// </summary>
        public static string FormSecondaryHeader {
            get {
                return ResourceManager.GetString("FormSecondaryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm.
        /// </summary>
        public static string FormSubmit {
            get {
                return ResourceManager.GetString("FormSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use suggested password.
        /// </summary>
        public static string FormSuggestPassword {
            get {
                return ResourceManager.GetString("FormSuggestPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Welcome!.
        /// </summary>
        public static string Greetings {
            get {
                return ResourceManager.GetString("Greetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Home.
        /// </summary>
        public static string HomeHeader {
            get {
                return ResourceManager.GetString("HomeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrect password.
        /// </summary>
        public static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на English.
        /// </summary>
        public static string LanguageSettingEnglish {
            get {
                return ResourceManager.GetString("LanguageSettingEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на App language.
        /// </summary>
        public static string LanguageSettingHeader {
            get {
                return ResourceManager.GetString("LanguageSettingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Russian.
        /// </summary>
        public static string LanguageSettingRussian {
            get {
                return ResourceManager.GetString("LanguageSettingRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на System language.
        /// </summary>
        public static string LanguageSettingSystem {
            get {
                return ResourceManager.GetString("LanguageSettingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ukrainian.
        /// </summary>
        public static string LanguageSettingUkrainian {
            get {
                return ResourceManager.GetString("LanguageSettingUkrainian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log In.
        /// </summary>
        public static string Log_In {
            get {
                return ResourceManager.GetString("Log_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please Log into your account.
        /// </summary>
        public static string LoginRequest {
            get {
                return ResourceManager.GetString("LoginRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generated password length.
        /// </summary>
        public static string PasswordLengthSettingHeader {
            get {
                return ResourceManager.GetString("PasswordLengthSettingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter password.
        /// </summary>
        public static string PasswordRequest {
            get {
                return ResourceManager.GetString("PasswordRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Undo.
        /// </summary>
        public static string PasswordResetBack {
            get {
                return ResourceManager.GetString("PasswordResetBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirmation code.
        /// </summary>
        public static string PasswordResetCode {
            get {
                return ResourceManager.GetString("PasswordResetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm.
        /// </summary>
        public static string PasswordResetConfirm {
            get {
                return ResourceManager.GetString("PasswordResetConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email.
        /// </summary>
        public static string PasswordResetEmail {
            get {
                return ResourceManager.GetString("PasswordResetEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fill all bottom fields.
        /// </summary>
        public static string PasswordResetHint {
            get {
                return ResourceManager.GetString("PasswordResetHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New password.
        /// </summary>
        public static string PasswordResetNewPassword {
            get {
                return ResourceManager.GetString("PasswordResetNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send code.
        /// </summary>
        public static string PasswordResetSendCode {
            get {
                return ResourceManager.GetString("PasswordResetSendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password reset.
        /// </summary>
        public static string PasswordResetTitle {
            get {
                return ResourceManager.GetString("PasswordResetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid code entered.
        /// </summary>
        public static string PasswordResetWrongCode {
            get {
                return ResourceManager.GetString("PasswordResetWrongCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search for passwords.
        /// </summary>
        public static string PlaceholderSearch {
            get {
                return ResourceManager.GetString("PlaceholderSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string PopupMenuEdit {
            get {
                return ResourceManager.GetString("PopupMenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove.
        /// </summary>
        public static string PopupMenuRemove {
            get {
                return ResourceManager.GetString("PopupMenuRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password normal.
        /// </summary>
        public static string PswdNormal {
            get {
                return ResourceManager.GetString("PswdNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password strong.
        /// </summary>
        public static string PswdStrong {
            get {
                return ResourceManager.GetString("PswdStrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password very strong.
        /// </summary>
        public static string PswdVeryStrong {
            get {
                return ResourceManager.GetString("PswdVeryStrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password very weak.
        /// </summary>
        public static string PswdVeryWeak {
            get {
                return ResourceManager.GetString("PswdVeryWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password weak.
        /// </summary>
        public static string PswdWeak {
            get {
                return ResourceManager.GetString("PswdWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Record was added.
        /// </summary>
        public static string RecordAddedNotification {
            get {
                return ResourceManager.GetString("RecordAddedNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Record was edited.
        /// </summary>
        public static string RecordEditedNotification {
            get {
                return ResourceManager.GetString("RecordEditedNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Record was removed.
        /// </summary>
        public static string RecordRemovedNotification {
            get {
                return ResourceManager.GetString("RecordRemovedNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remember me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string SettingsHeader {
            get {
                return ResourceManager.GetString("SettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sign Up.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Double click to copy.
        /// </summary>
        public static string TapToCopyToolTip {
            get {
                return ResourceManager.GetString("TapToCopyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copied to clipboard.
        /// </summary>
        public static string TextCopiedToClipboardNotification {
            get {
                return ResourceManager.GetString("TextCopiedToClipboardNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dark.
        /// </summary>
        public static string ThemeSettingDark {
            get {
                return ResourceManager.GetString("ThemeSettingDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на App theme.
        /// </summary>
        public static string ThemeSettingHeader {
            get {
                return ResourceManager.GetString("ThemeSettingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Light.
        /// </summary>
        public static string ThemeSettingLight {
            get {
                return ResourceManager.GetString("ThemeSettingLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на System.
        /// </summary>
        public static string ThemeSettingSystem {
            get {
                return ResourceManager.GetString("ThemeSettingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimize app to tray.
        /// </summary>
        public static string TraySettingHeader {
            get {
                return ResourceManager.GetString("TraySettingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string TwoStepAuthenticationCancel {
            get {
                return ResourceManager.GetString("TwoStepAuthenticationCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter 6-digit code that tou&apos;ve received by email.
        /// </summary>
        public static string TwoStepAuthenticationHint {
            get {
                return ResourceManager.GetString("TwoStepAuthenticationHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Submit.
        /// </summary>
        public static string TwoStepAuthenticationSubmit {
            get {
                return ResourceManager.GetString("TwoStepAuthenticationSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Two step authentication.
        /// </summary>
        public static string TwoStepAuthenticationTitle {
            get {
                return ResourceManager.GetString("TwoStepAuthenticationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User already exists.
        /// </summary>
        public static string UserExists {
            get {
                return ResourceManager.GetString("UserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User does not exists.
        /// </summary>
        public static string UserNotExists {
            get {
                return ResourceManager.GetString("UserNotExists", resourceCulture);
            }
        }
    }
}
